### ISSUE TITLE
[FlexView] about aligning things

### ISSUE THREAD

**Issue by lucacioria** [buildo/react-components#17]
situation that brought this thiking up:
![image](https://cloud.githubusercontent.com/assets/554092/9008588/9f22b1b4-379b-11e5-9836-6cdad203d9da.png)

how to approach this situation? possibilities:
- `margin-left: auto` on the right child works well (http://stackoverflow.com/questions/22429003/right-aligning-flex-item)
- `align-self` ?? couldn't get it to work..

@FrancescoCioria @giogonzo

**Comment by giogonzo** [comment]
Something like:

```scss
.parent {
  display: flex;
  flex-direction: row;
  justify-content: stretch;
  align-items: space-between;
  
  .left {
    flex: 0 0 30px;
  }
  
  .right {
    flex: 1 0 auto;
  }
}
```

doesn't work?
