### ISSUE TITLE
toaster (notifications manager)

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#74]
## requirements
discussed here: https://github.com/buildo/labonline/issues/730 + offline with pretty much everyone
final behavior: same as: http://igorprado.com/react-notification-system/ (but with a much nicer api!)
- display a list of dismissable notifications
- the list should be positioned at one of the corners top-left, top-right, etc (but we can start with top-right only), and stacking of toast notifications behave accordingly
  - e.g. for top-right, new notifications appear at the top of the stack and disappear at the bottom (FIFO) after a certain timeout.
- possible interaction is just "pausing" a specific item in the stack from disappearing automatically, how this interaction is initiated is delegated to the user / user component
  - when an item is paused, it will not disappear automatically, but other toasts in the stack behaves as they would so the entire stack can slide, including the "paused" toast
- items should be placed on top of everything and not interfer with the rest of the layout

## specs
- `Toaster` should have a stateless interface accepting ~ a list of children (all the toasts to be rendered / animated)
- internally, it is stateful and handles a timeout and a state (paused true/false) for each toast
- it should be able to accept a container element (id?) to be used as the container to render in
- should apply arbitrary animations (OSX?) for sliding and enter/leave, but consider this should be easily customizable in the future

**api draft**

**EDIT: old. look at comment below**
```js
<Toaster attachTo="#dasd">
  {(activeOn: fn, activeOff: fn, dismiss: fn) => errors.map(e => (
    <MyToastComponent
      key={uniqueToastKey(i)}
      onHover={activeOn}
      onHoverOut={activeOff}
      onDismissClick={dismiss(uniqueToastKey(i))}
    />
  )}
</Toaster>
```

**Comment by FrancescoCioria** [comment]
Actually the final API (**draft**) we had chosen was:

```js
<Toaster attachTo="#dasd" onEnterClassName="entering" onLeaveClassName="leaving" onMoveClassName="moving">
    {[
      <TimerToast
        key={uniqueToastKey(i)}
        onTimeOut={myCallback}
        duration={time_in_millis}
      />,
      ...
    ]}
</Toaster>
```

PS: I discussed it with @giogonzo and he agrees with the API above so I'm going to implement it this way. Stay tuned for further changes :)

**Comment by giogonzo** [comment]
TimerToast should accept a child though

**Comment by FrancescoCioria** [comment]
Also, what happens if/when there's no more space for new toasts on the page?
I would add a prop `onOverflow={callback}` to `Toaster`.
Do you agree @giogonzo ?

**Comment by giogonzo** [comment]
We shouldn't care too much, it's a remote edge case, and apps should handle
possibly long lists of errors at app level, aggregating

A safety callback is ok 👌

**Comment by FrancescoCioria** [comment]
@giogonzo 
While working with animation I've encountered some problems...
Inside the toaster I'm handling positioning by passing to the wrapper some inline style: 
- `transform: translate3d(0, index%, 0)`
- and also `transition: transform TIMEs EASE_FUNC` for the slide animation.

This last action turned out to be in conflict with `ReactCSSTransitionGroup` as it overwrites the transition defined in the utility animation classes of `ReactCSSTransitionGroup`...
Also the right way to achieve the enter/leave animation we want (slide in/out from right) would be using `translate3d` but this property too would be overwritten by `Toaster`...

I found two ways of solving these problems:
1)
- let user define "move transition" in css as he does for the rest
- use `right` property for slide in/out, but this means we have to set it as `!important` in order to overwrite `Toaster` inline style and also know the pixel size of the toasts

example:
```css
.toaster-anim { // I'm always passing transitionName as className to children to let user define transitions for default state
  -webkit-transition: -webkit-transform 0.3s ease-in-out;
  transition: transform 0.3s ease-in-out;
}

.toaster-anim-enter {
  opacity: 0.2;
  right: -240px !important; // toast width
  -webkit-transition: opacity .8s ease-out, right .8s ease-out;
  transition: opacity .8s ease-out, right .8s ease-out;
}

.toaster-anim-enter.toaster-anim-enter-active {
  opacity: 1;
  right: 0 !important;
  /*-webkit-transition: transform 0.3s ease-in-out*/
  /*transition: transform 0.3s ease-in-out;*/
}

.toaster-anim-leave {
    opacity: 1;
    right: 0 !important;
    -webkit-transition: opacity .8s ease-out, right .8s ease-out;
    transition: opacity .8s ease-out, right .8s ease-out;
}

.toaster-anim-leave.toaster-anim-leave-active {
    opacity: 0.01;
    right: -240px !important; // toast width
}
```

2)
use low-level component `ReactTransitionGroup` together with `ToastWrapper` component [(link to docs)](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup) and pass the style of each state (enter, enterActive ...) directly to `Toaster`.

In my opinion the 2º one is the correct way, but as I'm currently full of work I would implement the first one (which actually is already operative) and open another issue to improve it further on..

what do you think?
